services:
  minio:
    image: minio/minio:latest
    container_name: minio_nyc_jobs_audit
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=storage
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    ports:
      - "9001:9001"
      - "9000:9000"
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio_data:/data
    networks:
      - default

  prefect-server:
    image: prefecthq/prefect:3-latest
    container_name: prefect_server
    command: prefect server start
    ports:
      - "4200:4200"
    environment:
      PREFECT_API_URL: "http://prefect-server:4200/api"
  prefect-worker:
    image: prefecthq/prefect:3-latest
    container_name: prefect_worker
    command: prefect worker start --pool data_ingestion
    environment:
      PREFECT_API_URL: "http://prefect-server:4200/api"

volumes:
  minio_data:

networks:
  default:
